# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0002_post_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
