# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0003_auto_20171124_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='book_review',
        ),
    ]
