# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0005_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
