# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0006_auto_20171201_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
